service: test-api
frameworkVersion: '2'
provider:
  name: aws
  region: 'eu-west-1'
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: get
